### PR TITLE
flowable ?

### PR DESCRIPTION
**Pull request by karesti**

### CODE REVIEW

**Comment by tsegismont** [comment]
LGTM

**Comment by karesti** [comment]
@galderz I changed to one single instance on infinispan. I wonder we need to have 3 instances for the deepdive

**Comment by karesti** [comment]
@galderz I was struggling with the resources and I comited the file, I can revert this before merge
wdyt ?

**Comment by galderz** [comment]
> @galderz I changed to one single instance on infinispan. I wonder we need to have 3 instances for the deepdive

Why did you change to one instance? What happens if that one node goes down? The core of what we do is based around having a cluster of Infinispan instances. Without that, might as well use any of the off the self standalone local caching servers out there ;)

**Comment by galderz** [comment]
> @galderz I was struggling with the resources and I comited the file, I can revert this before merge
wdyt ?

If struggling with resources, why not get rid of kafka? ;)

**Comment by galderz** [comment]
I'll test it later and see how it goes.

**Comment by karesti** [comment]
@galderz you kwnow why ! haha I was struggling locally I think more due to my conf on docker but I just wanted to test this fast enough ! Im going to reput 3 nodes back

**Comment by galderz** [comment]
With this change trains appear gradually in the dashboard 👍

**Comment by galderz** [comment]
Tested and looks good :) 

Thx for quick turnaround @karesti !

**Pull request merged**
