### PR TITLE
Switch Java FX dashboard to a web view

### PR DESCRIPTION
**Pull request by tsegismont**
Do not merge yet. I wanted to share the first commit to gather feeback.

TODO:
- refactor to JS modules
- build with webpack
- Add Dockerfile
- Deploy to Openshift

### CODE REVIEW

**Comment by galderz** [comment]
Are you expecting to integrate this for Codemotion Madrid? I think it'd a bit late for that. I don't have much time to spend on this until Friday after my talk.

**Comment by tsegismont** [comment]
No I don't. But in French we say "strike the iron while it's hot", so I
started this project and shared it to gather feedback.

2017-11-22 9:21 GMT+01:00 Galder Zamarreño <notifications@github.com>:

**Comment by galderz** [comment]
Looking into this. How do you run it?

**Comment by tsegismont** [comment]
So far I've run it only from IntelliJ (run on browser). The PR is not
ready, the project misses a build file and webpack setup.

2018-01-08 8:43 GMT+01:00 Galder Zamarreño <notifications@github.com>:

**Comment by galderz** [comment]
Looks good so far. Managed to get it running.

Do you want me to integrate? Or do you want to add other remaining bits?

**Comment by tsegismont** [comment]
Thanks for taking a look.

I'm busy on Vert.x 3.5.1 ATM...:

- we can wait for me to get more bandwith to setup webpack and integrate
the module to the build, or
- I can push the branch to the parent GH project and someone else takes it
over

**Comment by galderz** [comment]
I think it's better if we wait until it's complete. There's no massive runs for this. I'll close it for now, you can reopen it when you get around to completing the rest of bits.

**Pull request closed without merging**
